services:
  web:
    build: .
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
